language: node_js
sudo: required
branches:
  only:
  - master
  - "/^issue.*$/"
  - /^greenkeeper/.*$/
node_js:
- '8'
- '10'
os:
- linux
- osx
osx_image: xcode9

before_install:
  - git clone https://github.com/IBM-Swift/Package-Builder.git

script:
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
